### ISSUE TITLE
Bubbled scrollwheel events

### ISSUE THREAD

**Issue by cycle4passion** [bagusindrayana/scrollpage-js#3] opened 2022-02-19 20:00 UTC
They appear to be recognized, but do not fire page scroll functionality.

https://codepen.io/c4p/pen/ZEaxbxx?editors=1111

**Comment by bagusindrayana** [comment] 2022-02-24 14:50
thanks for the report and sorry for the late reply, for now the cause of the bug is if the "page" element of "main-page" has a child, I've found the solution and now testing it for scroll function on desktop and touch/swipe function on mobile and will be fixed in the next update

**Comment by bagusindrayana** [comment] 2022-02-26 13:56
I've released version 0.1.3 and it's fixed (I've tried it on desktop and mobile, maybe need to try in some cases and conditions), you can try it and if there are other problems please report me I will try to fix it.

In the future I will make some better examples using all the features available.

**Comment by cycle4passion** [comment] 2022-02-26 14:40
Works for the previous example above, but does not accomodate overflow: scroll in div. Not sure if you wanted to cover that or not. Most of the other pagescroll utils allow you to scroll over div but when it reaches end scrollpage fired.

[Codepen](https://codepen.io/c4p/pen/LYOJBVZ?editors=1111)

If you decide to implement, it might be worthy of another setting, something like "allowChildrenToScroll" defaulting to true, but if set to false scrollpage-js changes pages immediately (as currently).

**Comment by bagusindrayana** [comment] 2022-02-26 23:29
thank you for the suggestions and reports I will soon add some features in the future to cover the shortcomings of this library

**Comment by bagusindrayana** [comment] 2022-03-04 06:28
> Works for the previous example above, but does not accomodate overflow: scroll in div. Not sure if you wanted to cover that or not. Most of the other pagescroll utils allow you to scroll over div but when it reaches end scrollpage fired.
> 
> [Codepen](https://codepen.io/c4p/pen/LYOJBVZ?editors=1111)
> 
> If you decide to implement, it might be worthy of another setting, something like "allowChildrenToScroll" defaulting to true, but if set to false scrollpage-js changes pages immediately (as currently).

i already make demo with [scrolling content ](https://scrollpage-js.netlify.app/examples/scroll-content.html) for next version

**Comment by bagusindrayana** [comment] 2022-03-06 04:10
> Works for the previous example above, but does not accomodate overflow: scroll in div. Not sure if you wanted to cover that or not. Most of the other pagescroll utils allow you to scroll over div but when it reaches end scrollpage fired.
> 
> [Codepen](https://codepen.io/c4p/pen/LYOJBVZ?editors=1111)
> 
> If you decide to implement, it might be worthy of another setting, something like "allowChildrenToScroll" defaulting to true, but if set to false scrollpage-js changes pages immediately (as currently).

i try fix in [v0.1.4](https://github.com/bagusindrayana/scrollpage-js/releases/tag/v0.1.4) all children will be able scrolling if have overflow and add options `triggerScrollChildren` this will trigger scrollpage if scrolling content reach bottom or top (default false)

**Closed as completed by bagusindrayana** 2022-03-06 04:10 UTC
Labels: bug
